#include "core.h"
int main(int argc, char **argv)
{
	const gchar *ui =
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		"<interface>"
		"<requires lib=\"gtk+\" version=\"2.24\"/>"
		"<!-- interface-naming-policy project-wide -->"
		"<object class=\"GtkAboutDialog\" id=\"aboutdialog\">"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"border_width\">5</property>"
		"<property name=\"title\" translatable=\"yes\">\303\200 propos</property>"
		"<property name=\"window_position\">center</property>"
		"<property name=\"destroy_with_parent\">True</property>"
		"<property name=\"type_hint\">dialog</property>"
		"<property name=\"skip_taskbar_hint\">True</property>"
		"<property name=\"deletable\">False</property>"
		"<property name=\"has_separator\">True</property>"
		"<property name=\"program_name\">Simulateur de Tourniquet</property>"
		"<property name=\"version\">3.0</property>"
		"<property name=\"copyright\" translatable=\"yes\">Aucun droit r\303\251serv\303\251</property>"
		"<property name=\"comments\" translatable=\"yes\">Mini projet E.M.S.I. 2011/2012</property>"
		"<property name=\"website\">http://www.emsimarrakech.ma</property>"
		"<property name=\"authors\">ERRAJAI Mouhssine\n"
		"ELAZZAM Abdeslam\n"
		"BELATAR Mohammed Ousama</property>"
		"<child internal-child=\"vbox\">"
		"<object class=\"GtkVBox\" id=\"dialog-vbox1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"spacing\">2</property>"
		"<child internal-child=\"action_area\">"
		"<object class=\"GtkHButtonBox\" id=\"dialog-action_area1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"layout_style\">end</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"pack_type\">end</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<placeholder/>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"<object class=\"GtkAdjustment\" id=\"commutation\">"
		"<property name=\"upper\">10</property>"
		"<property name=\"step_increment\">1</property>"
		"<property name=\"page_increment\">10</property>"
		"</object>"
		"<object class=\"GtkListStore\" id=\"logstore\">"
		"<columns>"
		"<!-- column-name Temps -->"
		"<column type=\"guint\"/>"
		"<!-- column-name Processus -->"
		"<column type=\"gchararray\"/>"
		"<!-- column-name \303\211v\303\250nement -->"
		"<column type=\"gchararray\"/>"
		"</columns>"
		"<data>"
		"<row>"
		"<col id=\"0\">0</col>"
		"<col id=\"1\" translatable=\"yes\">Bienvenue</col>"
		"<col id=\"2\" translatable=\"yes\">Remplissez vos procesuss et lancer la simulation</col>"
		"</row>"
		"</data>"
		"</object>"
		"<object class=\"GtkListStore\" id=\"mainstore\">"
		"<columns>"
		"<!-- column-name Nom -->"
		"<column type=\"gchararray\"/>"
		"<!-- column-name Arriv\303\251e -->"
		"<column type=\"guint\"/>"
		"<!-- column-name Temps -->"
		"<column type=\"guint\"/>"
		"</columns>"
		"<data>"
		"<row>"
		"<col id=\"0\" translatable=\"yes\">P1</col>"
		"<col id=\"1\">0</col>"
		"<col id=\"2\">1</col>"
		"</row>"
		"<row>"
		"<col id=\"0\" translatable=\"yes\">P2</col>"
		"<col id=\"1\">0</col>"
		"<col id=\"2\">2</col>"
		"</row>"
		"<row>"
		"<col id=\"0\" translatable=\"yes\">P3</col>"
		"<col id=\"1\">1</col>"
		"<col id=\"2\">1</col>"
		"</row>"
		"</data>"
		"</object>"
		"<object class=\"GtkAdjustment\" id=\"quantum\">"
		"<property name=\"lower\">1</property>"
		"<property name=\"upper\">100</property>"
		"<property name=\"value\">1</property>"
		"<property name=\"step_increment\">1</property>"
		"<property name=\"page_increment\">10</property>"
		"</object>"
		"<object class=\"GtkListStore\" id=\"statstore\">"
		"<columns>"
		"<!-- column-name Nom -->"
		"<column type=\"gchararray\"/>"
		"<!-- column-name Fin -->"
		"<column type=\"guint\"/>"
		"<!-- column-name S\303\251jour -->"
		"<column type=\"guint\"/>"
		"<!-- column-name Attente -->"
		"<column type=\"guint\"/>"
		"</columns>"
		"</object>"
		"<object class=\"GtkAdjustment\" id=\"temps_arrivee\">"
		"<property name=\"upper\">1.7976931348623157e+308</property>"
		"<property name=\"step_increment\">1</property>"
		"<property name=\"page_increment\">10</property>"
		"</object>"
		"<object class=\"GtkAdjustment\" id=\"temps_execution\">"
		"<property name=\"lower\">1</property>"
		"<property name=\"upper\">1.7976931348623157e+308</property>"
		"<property name=\"step_increment\">1</property>"
		"<property name=\"page_increment\">10</property>"
		"</object>"
		"<object class=\"GtkWindow\" id=\"window\">"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkVBox\" id=\"vbox1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkHBox\" id=\"hbox1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkVBox\" id=\"vbox2\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkMenuBar\" id=\"menubar1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"ubuntu_local\">True</property>"
		"<child>"
		"<object class=\"GtkMenuItem\" id=\"menuitem1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"label\" translatable=\"yes\">_File</property>"
		"<property name=\"use_underline\">True</property>"
		"<child type=\"submenu\">"
		"<object class=\"GtkMenu\" id=\"menu1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"ubuntu_local\">True</property>"
		"<child>"
		"<object class=\"GtkImageMenuItem\" id=\"imagemenuitem1\">"
		"<property name=\"label\">gtk-new</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"use_underline\">True</property>"
		"<property name=\"use_stock\">True</property>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkImageMenuItem\" id=\"imagemenuitem2\">"
		"<property name=\"label\">gtk-open</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"use_underline\">True</property>"
		"<property name=\"use_stock\">True</property>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkImageMenuItem\" id=\"imagemenuitem3\">"
		"<property name=\"label\">gtk-save</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"use_underline\">True</property>"
		"<property name=\"use_stock\">True</property>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkSeparatorMenuItem\" id=\"separatormenuitem1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkImageMenuItem\" id=\"imagemenuitem5\">"
		"<property name=\"label\">gtk-quit</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"use_underline\">True</property>"
		"<property name=\"use_stock\">True</property>"
		"</object>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkMenuItem\" id=\"menuitem4\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"label\" translatable=\"yes\">_Help</property>"
		"<property name=\"use_underline\">True</property>"
		"<child type=\"submenu\">"
		"<object class=\"GtkMenu\" id=\"menu3\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"ubuntu_local\">True</property>"
		"<child>"
		"<object class=\"GtkImageMenuItem\" id=\"imagemenuitem10\">"
		"<property name=\"label\">gtk-about</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"use_underline\">True</property>"
		"<property name=\"use_stock\">True</property>"
		"</object>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkScrolledWindow\" id=\"scrolledwindow1\">"
		"<property name=\"width_request\">222</property>"
		"<property name=\"height_request\">150</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"hscrollbar_policy\">automatic</property>"
		"<property name=\"vscrollbar_policy\">automatic</property>"
		"<child>"
		"<object class=\"GtkTreeView\" id=\"mainlist\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"model\">mainstore</property>"
		"<property name=\"headers_clickable\">False</property>"
		"<property name=\"reorderable\">True</property>"
		"<property name=\"rules_hint\">True</property>"
		"<property name=\"enable_search\">False</property>"
		"<property name=\"search_column\">0</property>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"col1\">"
		"<property name=\"resizable\">True</property>"
		"<property name=\"title\" translatable=\"yes\">Nom</property>"
		"<child>"
		"<object class=\"GtkCellRendererText\" id=\"cellrenderertext1\">"
		"<property name=\"editable\">True</property>"
		"</object>"
		"<attributes>"
		"<attribute name=\"text\">0</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"col2\">"
		"<property name=\"resizable\">True</property>"
		"<property name=\"title\" translatable=\"yes\">Arriv\303\251e</property>"
		"<child>"
		"<object class=\"GtkCellRendererSpin\" id=\"cellrendererspin1\">"
		"<property name=\"editable\">True</property>"
		"<property name=\"adjustment\">temps_arrivee</property>"
		"</object>"
		"<attributes>"
		"<attribute name=\"text\">1</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"col3\">"
		"<property name=\"resizable\">True</property>"
		"<property name=\"title\" translatable=\"yes\">Temps</property>"
		"<child>"
		"<object class=\"GtkCellRendererSpin\" id=\"cellrendererspin2\">"
		"<property name=\"editable\">True</property>"
		"<property name=\"adjustment\">temps_execution</property>"
		"</object>"
		"<attributes>"
		"<attribute name=\"text\">2</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">True</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"position\">1</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkHButtonBox\" id=\"hbuttonbox1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkButton\" id=\"button1\">"
		"<property name=\"label\">gtk-add</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"receives_default\">True</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"use_stock\">True</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkButton\" id=\"button2\">"
		"<property name=\"label\">gtk-remove</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"receives_default\">True</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"use_stock\">True</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">1</property>"
		"</packing>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">2</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkVBox\" id=\"vbox3\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkHBox\" id=\"hbox2\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkLabel\" id=\"label3\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"label\" translatable=\"yes\">Quantum</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkHScale\" id=\"hscale1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"adjustment\">quantum</property>"
		"<property name=\"round_digits\">0</property>"
		"<property name=\"digits\">0</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">True</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"padding\">2</property>"
		"<property name=\"position\">1</property>"
		"</packing>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkHBox\" id=\"hbox3\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkLabel\" id=\"label4\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"label\" translatable=\"yes\">Commutation</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkHScale\" id=\"hscale2\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"adjustment\">commutation</property>"
		"<property name=\"round_digits\">0</property>"
		"<property name=\"digits\">0</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">True</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"padding\">2</property>"
		"<property name=\"position\">1</property>"
		"</packing>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">1</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkHButtonBox\" id=\"hbuttonbox2\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkButton\" id=\"button3\">"
		"<property name=\"label\">gtk-execute</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"receives_default\">True</property>"
		"<property name=\"use_action_appearance\">False</property>"
		"<property name=\"use_stock\">True</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">2</property>"
		"</packing>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">3</property>"
		"</packing>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">True</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkVSeparator\" id=\"vseparator1\">"
		"<property name=\"width_request\">10</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"position\">1</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkVBox\" id=\"vbox4\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<child>"
		"<object class=\"GtkLabel\" id=\"label1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"label\" translatable=\"yes\">Statistiques</property>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkScrolledWindow\" id=\"scrolledwindow3\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"hscrollbar_policy\">automatic</property>"
		"<property name=\"vscrollbar_policy\">automatic</property>"
		"<child>"
		"<object class=\"GtkTreeView\" id=\"statlist\">"
		"<property name=\"width_request\">222</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"model\">statstore</property>"
		"<property name=\"headers_clickable\">False</property>"
		"<property name=\"rules_hint\">True</property>"
		"<property name=\"enable_search\">False</property>"
		"<property name=\"search_column\">0</property>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn6\">"
		"<property name=\"title\" translatable=\"yes\">Nom</property>"
		"<child>"
		"<object class=\"GtkCellRendererText\" id=\"cellrenderertext4\">"
		"<property name=\"alignment\">center</property>"
		"</object>"
		"<attributes>"
		"<attribute name=\"text\">0</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"Fin\">"
		"<property name=\"title\" translatable=\"yes\">Fin</property>"
		"<child>"
		"<object class=\"GtkCellRendererText\" id=\"cellrenderertext7\">"
		"<property name=\"alignment\">center</property>"
		"</object>"
		"<attributes>"
		"<attribute name=\"text\">1</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn7\">"
		"<property name=\"title\" translatable=\"yes\">S\303\251jour</property>"
		"<child>"
		"<object class=\"GtkCellRendererText\" id=\"cellrenderertext5\">"
		"<property name=\"alignment\">center</property>"
		"</object>"
		"<attributes>"
		"<attribute name=\"text\">2</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn8\">"
		"<property name=\"title\" translatable=\"yes\">Attente</property>"
		"<child>"
		"<object class=\"GtkCellRendererText\" id=\"cellrenderertext6\">"
		"<property name=\"alignment\">center</property>"
		"</object>"
		"<attributes>"
		"<attribute name=\"text\">3</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">True</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"position\">1</property>"
		"</packing>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">True</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"position\">2</property>"
		"</packing>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">True</property>"
		"<property name=\"fill\">True</property>"
		"<property name=\"position\">0</property>"
		"</packing>"
		"</child>"
		"<child>"
		"<object class=\"GtkExpander\" id=\"expander1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<child>"
		"<object class=\"GtkScrolledWindow\" id=\"scrolledwindow2\">"
		"<property name=\"height_request\">172</property>"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"hscrollbar_policy\">automatic</property>"
		"<property name=\"vscrollbar_policy\">automatic</property>"
		"<child>"
		"<object class=\"GtkTreeView\" id=\"treeview1\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">True</property>"
		"<property name=\"model\">logstore</property>"
		"<property name=\"headers_visible\">False</property>"
		"<property name=\"headers_clickable\">False</property>"
		"<property name=\"search_column\">0</property>"
		"<property name=\"enable_grid_lines\">vertical</property>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn4\">"
		"<property name=\"title\" translatable=\"yes\">column</property>"
		"<child>"
		"<object class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/>"
		"<attributes>"
		"<attribute name=\"text\">0</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn1\">"
		"<property name=\"title\" translatable=\"yes\">column</property>"
		"<child>"
		"<object class=\"GtkCellRendererText\" id=\"cellrenderertext8\"/>"
		"<attributes>"
		"<attribute name=\"text\">1</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"<child>"
		"<object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn5\">"
		"<property name=\"title\" translatable=\"yes\">column</property>"
		"<child>"
		"<object class=\"GtkCellRendererText\" id=\"cellrenderertext3\"/>"
		"<attributes>"
		"<attribute name=\"text\">2</attribute>"
		"</attributes>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"</child>"
		"<child type=\"label\">"
		"<object class=\"GtkLabel\" id=\"label2\">"
		"<property name=\"visible\">True</property>"
		"<property name=\"can_focus\">False</property>"
		"<property name=\"label\" translatable=\"yes\">Journal d'\303\251v\303\250nements</property>"
		"</object>"
		"</child>"
		"</object>"
		"<packing>"
		"<property name=\"expand\">False</property>"
		"<property name=\"fill\">False</property>"
		"<property name=\"position\">1</property>"
		"</packing>"
		"</child>"
		"</object>"
		"</child>"
		"</object>"
		"</interface>";
	Data d;
	GObject *r;
	GtkBuilder *builder;
	gtk_init(&argc, &argv);
	builder = gtk_builder_new();
// 	gtk_builder_add_from_file(builder, UI_FILE, NULL);
	gtk_builder_add_from_string(builder, ui , -1, NULL);
	d.statstore = GTK_LIST_STORE(gtk_builder_get_object(builder, "statstore"));
	d.logstore = GTK_LIST_STORE(gtk_builder_get_object(builder, "logstore"));
	d.mainlist = GTK_TREE_VIEW(gtk_builder_get_object(builder, "mainlist"));
	d.quantum = GTK_ADJUSTMENT(gtk_builder_get_object(builder, "quantum"));
	d.window = GTK_WIDGET(gtk_builder_get_object(builder, "window"));
	d.delta = GTK_ADJUSTMENT(gtk_builder_get_object(builder, "commutation"));
	
	r = gtk_builder_get_object(builder,"cellrenderertext1");
	g_object_set_data(r, "colnum", GUINT_TO_POINTER(COL_NOM));
	g_signal_connect(r, "edited", G_CALLBACK(cell_edited), gtk_tree_view_get_model(d.mainlist));

	r = gtk_builder_get_object(builder,"cellrendererspin1");
	g_object_set_data(r, "colnum", GUINT_TO_POINTER(COL_TEMPS_ARRIVEE));
	g_signal_connect(r, "edited", G_CALLBACK(cell_edited), gtk_tree_view_get_model(d.mainlist));

	r = gtk_builder_get_object(builder,"cellrendererspin2");
	g_object_set_data(r, "colnum", GUINT_TO_POINTER(COL_TEMPS_EXECUTION));
	g_signal_connect(r, "edited", G_CALLBACK(cell_edited), gtk_tree_view_get_model(d.mainlist));
	g_object_unref(r);

	
	g_signal_connect_swapped(gtk_builder_get_object(builder, "imagemenuitem5"),
							 "activate", G_CALLBACK(gtk_main_quit), NULL);
	g_signal_connect(d.window,
					 "delete-event", G_CALLBACK(gtk_main_quit), NULL);
	g_signal_connect(gtk_builder_get_object(builder,"button2"),
					 "clicked", G_CALLBACK(remove_item), d.mainlist);
	g_signal_connect(gtk_builder_get_object(builder, "button3"),
					 "clicked", G_CALLBACK(play_clicked), &d);
	g_signal_connect(gtk_builder_get_object(builder,"button1"),
					 "clicked", G_CALLBACK(add_item), gtk_tree_view_get_model(d.mainlist));
	g_signal_connect(gtk_builder_get_object(builder, "imagemenuitem1"),
					 "activate", G_CALLBACK(clear_list), gtk_tree_view_get_model(d.mainlist));

	r = gtk_builder_get_object(builder, "aboutdialog");
#ifndef WIN_32
	gtk_about_dialog_set_logo(GTK_ABOUT_DIALOG(r), gdk_pixbuf_new_from_inline(-1, emsi_logo, FALSE, NULL));
#endif
	g_signal_connect(gtk_builder_get_object(builder, "imagemenuitem10"), "activate", G_CALLBACK(apropos), r);
	g_object_unref(r);
	
	g_signal_connect(gtk_builder_get_object(builder, "imagemenuitem2"),
					 "activate", G_CALLBACK(open_clicked), &d);
	g_signal_connect(gtk_builder_get_object(builder, "imagemenuitem3"),
					 "activate", G_CALLBACK(save_clicked), &d);
	gtk_window_set_title(GTK_WINDOW(d.window), "Simulateur Round Robin");
	gtk_widget_show_all(d.window);
	gtk_main();
    return 0;
}
